### ISSUE TITLE
Tags disappear when changing page.

### ISSUE THREAD

**Issue by MalinAan** [devilry/trix#9]
When you try to switch page, it removes all the tags you have chosen.

For example; when I select the tag _infx1005_ and try to go to page 2, it removes all the selected (extra) taggs, and I get all the assignments that exist, instead of only those assignments that are tagged with _infx1005_.

**Comment by MalinAan** [comment]
Found a workaround; hard-coded the desired page and the desired tag like this: https://trix.ifi.uio.no/course/1?page=2&tags=infx1005%2Cvår2017

**Comment by torgeirl** [comment]
Hi @MalinAan,

This repository is for Trix 1.x while I assume you're referring to an issue for [Trix 2.x](https://github.com/devilry/trix2/). That's the reason you haven't gotten an answer earlier.

The problem was actually solved in `v2.0.9` (via https://github.com/devilry/trix2/issues/18), but that hasn't been in production for some reason. The issue should however be fixed when the server is updated to `v2.1.0` (ETA this or next week).
